const fs = require("fs");
const path = require("path");
const cheerio = require("cheerio");
const prettier = require("prettier");
const htmlMinifier = require("html-minifier-next");
const { MINIFY, SRC_DIR, OUT_DIR, libraries } = require("../constants");

/** @param {cheerio.CheerioAPI} $  */
async function writeHTA($) {
    let out;

    if (MINIFY) {
        out = await htmlMinifier.minify($.html(), {
            collapseWhitespace: true,
            minifyJS: {
                engine: "terser",
                ie8: true,
                compress: true,
                mangle: true
            },
            minifyCSS: true,
            minifySVG: true,
            removeComments: true,
            removeAttributeQuotes: true,
            removeRedundantAttributes: true,
            removeEmptyAttributes: true,
            removeOptionalTags: true
        });
    } else {
        out = await prettier.format($.html(), {
            parser: "html",
            tabWidth: 4,
            singleQuote: false,
            trailingComma: "none",
            printWidth: 120
        });
    }

    out =
        "<!--\n" +
        `    Generated by TS2HTA @ ${Date.now()}\n` +
        `    Build is ${MINIFY ? "" : "NOT "}minified\n` +
        `    Libraries: ${libraries.map((lib) => path.basename(lib)).join(", ")}\n` +
        "-->\n" +
        out;

    fs.writeFileSync(path.join(OUT_DIR, "app.hta"), out, "utf8");
    fs.writeFileSync(path.join(OUT_DIR, "app.html"), out, "utf8");
}

module.exports = function () {
    const html = fs.readFileSync(path.resolve(SRC_DIR, "app.html"), "utf8");
    const js = fs.readFileSync(path.join(OUT_DIR, "_app.js"), "utf8");

    const $ = cheerio.load(html);
    $("html").attr("xmlns", "http://www.w3.org/1999/xhtml");
    $("head").prepend(`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`);
    $("body").attr("scroll", "auto");

    // css
    fs.readdirSync(SRC_DIR, { recursive: true })
        .filter((f) => f.endsWith(".css"))
        .forEach((f) => {
            const file = path.join(SRC_DIR, f);
            const body = fs.readFileSync(file, "utf8");
            $("head")
                .append(`<!-- ${path.basename(file)} -->\n`)
                .append(`<style>\n${body}\n</style>`);
        });

    // js
    libraries.forEach((dep) => {
        const body = fs.readFileSync(dep, "utf8");
        $("body")
            .append(`<!-- ${path.basename(dep)} -->\n`)
            .append(`<script>\n${body}\n</script>`);
    });
    $("body").append(`<script>\n${js}\n</script>`);

    writeHTA($);
};
